-- PIVOT & UNPIVOT
-- PIVOT 이란?
-- 행을 열로 변환할 때, GROUP BY, 집계, CASE문을 사용해서 변환합니다 =-> PIVOT으로 쉽게 변환
-- GROUP BY를 통해서 테이블을 정리, FROM절을 통해서 값ㄱ을 구분하여 조건장으로 만들어서 컬럼명과 IN으로 값을 생성

-- CATS : CREATE TABLE 테이블명 AS SELECT 생성할 쿼리
-- CVAS : CREATE VIEW 테이블명 AS SELECT 생성할 쿼리

-- Sample Data : 날짜 가지고 있는 테이블을 만듦
CREATE TABLE DATE_TEMP AS SELECT TO_DATE('20260101','YYYYMMDD') + LEVEL -1 DDATE
							FROM DUAL
							CONNECT BY LEVEL -1 <= TO_DATE('20261231', 'YYYYMMDD') - TO_DATE('20260101','YYYYMMDD');

SELECT TO_CHAR(dt.DDATE ,'YYYYMMDD')
	FROM DATE_TEMP dt;

-- 각 월이 몇 일로 구성이 되어 있는지 세로 -> 가로 데이터로 변경
-- SUM, GROUP BY는 월, TO_CHAR 월만 추출, CASE문, ALIAS

SELECT TO_CHAR(DDATE, 'YYYY') 년도,
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '01'THEN 1 ELSE 0 END) AS "01M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '02'THEN 1 ELSE 0 END) AS "02M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '03'THEN 1 ELSE 0 END) AS "03M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '04'THEN 1 ELSE 0 END) AS "04M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '05'THEN 1 ELSE 0 END) AS "05M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '06'THEN 1 ELSE 0 END) AS "06M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '07'THEN 1 ELSE 0 END) AS "07M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '08'THEN 1 ELSE 0 END) AS "08M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '09'THEN 1 ELSE 0 END) AS "09M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '10'THEN 1 ELSE 0 END) AS "10M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '11'THEN 1 ELSE 0 END) AS "11M",
	SUM(CASE TO_CHAR(DDATE,'MM') WHEN '12'THEN 1 ELSE 0 END) AS "12M"
	FROM DATE_TEMP dt
	GROUP BY TO_CHAR(DDATE, 'YYYY');

-- PIVOT

SELECT *
	FROM(SELECT TO_CHAR(DDATE, 'YYYY') 년도,
			DECODE(TO_CHAR(DDATE, 'MM'),'01','1월','02','2월','03','3월','04','4월','05','5월','06','6월'
			,'07','7월','08','8월','09','9월','10','10월','11','11월','12','12월') AS MON,
			DDATE
		FROM DATE_TEMP dt
	)
	PIVOT
	(
		COUNT(DDATE) FOR MON IN('1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월')
	);

CREATE TABLE STUDENT( 
	JOIN_MONTH VARCHAR2(10),
	NAME VARCHAR2(100)
);

INSERT INTO STUDENT(JOIN_MONTH, NAME)
	SELECT '1월', '트레이서' FROM DUAL
	UNION ALL
	SELECT '1월', '겐지' FROM DUAL
	UNION ALL
	SELECT '1월', '메르시' FROM DUAL
	UNION ALL
	SELECT '2월', '리퍼' FROM DUAL
	UNION ALL
	SELECT '2월', '한조' FROM DUAL
	UNION ALL
	SELECT '2월', '윈스턴' FROM DUAL;

SELECT *
	FROM STUDENT s;

SELECT *
	FROM STUDENT s
	PIVOT (COUNT(JOIN_MONTH) FOR JOIN_MONTH IN('1월', '2월'));

-- WITH AS 문법 가상으로 테이블을 만들어서 테스트 할 때 사용한다
WITH TEMP AS (
	SELECT 1 AS COL1, 2 AS COL2, 3 AS COL3 FROM DUAL
)
SELECT COL_NM, COL_VAL
	FROM(
		SELECT * 
			FROM TEMP
	)
	UNPIVOT( 
		COL_VAL FOR COL_NM IN (COL1,COL2, COL3)
	);



