-- 그룹함수 GROUP BY 절 + 소계와 총계를 출력한다
-- GROUP 함수 -> 통계함수(ROLLUP, CUBE, GROUPING SETS)

-- GROUP BY와 통계함수의 차이점
-- 결론 : 작성하는 순서에 영향을 받는다
-- Q. 부서명(DNAME)과 업무명(JOB)을 기준으로 사원수와 급여 합을 집계
SELECT DNAME, JOB
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY DNAME, JOB
	ORDER BY 1;

SELECT DNAME, JOB
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY JOB, DNAME
	ORDER BY 1;

-- 결론 : GROUP BY의 컬럼은 순서에 상관이 없다!!!!

-- 통계 : 소계와 총계 - UNION ALL로 작성해 보자
-- 시나리오 : 
--	출력 SELECT
--	UNOIN ALL
--	소계	SUM
--	UNOIN ALL
--	출력
--	UNOIN ALL
--	소계
--		총계
-- Q. 부서 + 업무별 "개수-COUNT" "급여합-SUM" 통계
SELECT DNAME, JOB, COUNT(*) "DNAME+JOB", SUM(SAL) "DNAME+JOB 급여합"
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY DNAME, JOB
UNION ALL
-- 부서 개수 급여합
SELECT DNAME, ' ', COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY DNAME
UNION ALL
-- 업무 개수 급여합
SELECT ' ', JOB, COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY JOB
UNION ALL
-- 전체총계
SELECT '전체', ' ', COUNT(*), SUM(SAL)
	FROM EMP
ORDER BY 1 , 2;

------------------------------------------------------------
-- ROLLUP을 통해서 작성해 보자
-- 결론 : ROLLUP을 사용할 때는 순서가 중요하다
SELECT DNAME, COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY ROLLUP(DNAME);

--DNAME을 기준으로 JOB의 통계정보를 출력하자
SELECT DNAME, JOB, COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY ROLLUP(DNAME, JOB)
	ORDER BY DNAME, JOB;

-- JOB을 기준으로 DNAME의 통계 정보를 출력
SELECT JOB, DNAME, COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY ROLLUP(JOB, DNAME)
	ORDER BY JOB, DNAME;

--SQLD 시험에 나오는 코드
SELECT JOB, DNAME, COUNT(*), SUM(SAL)
 	FROM EMP e JOIN DEPT d
 	USING(DEPTNO)
	GROUP BY JOB, ROLLUP(DNAME)
	ORDER BY 1, 2;

SELECT DNAME, JOB, COUNT(*), SUM(SAL)
 	FROM EMP e JOIN DEPT d
 	USING(DEPTNO)
	GROUP BY DNAME, ROLLUP(JOB)
	ORDER BY 1, 2;
 
 --GROUP BY는 작성에는 순서가 없고, ROLLUP의 컬럼이 통계의 대상이 된다
SELECT DNAME, JOB, COUNT(*), SUM(SAL)
 	FROM EMP e JOIN DEPT d
 	USING(DEPTNO)
	GROUP BY ROLLUP(JOB), DNAME
	ORDER BY 1, 2;
 
 --------------------- GROUPING은 GROUP되어 있는 항목을 값으로 처리해줌
 -- ROLLUP으러 생성된 컬럼의 경우 1, 아닌 경우 0
 -- 결론  JOB으로만 통계가 발생 GROUPING(DNAME) : 0 , GROUPING(JOB) : 1
 --		 DNAME(상위) 통계가 발생 GROUPING(DNAME) : 1 , GROUPING(JOB) : 1
SELECT DNAME, JOB, 
 	GROUPING(DNAME), GROUPING(JOB),
 	COUNT(*), SUM(SAL)
 	FROM EMP e JOIN DEPT d
 	USING(DEPTNO)
 	GROUP BY ROLLUP(DNAME, JOB)
 	ORDER BY 1;

 -- GROUPING으로 나온 0과 1의 값을 CASE문을 통해 사용자가 쉽게 알아볼 수 있도록 만들자
 SELECT --DNAME, JOB, 
 	CASE GROUPING(DNAME) WHEN 1 THEN '모든부서' ELSE DNAME END AS 부서 , 
 	CASE GROUPING(JOB) WHEN 1 THEN '모든업무' ELSE JOB END AS 업무, 
 	COUNT(*), SUM(SAL)
 	FROM EMP e JOIN DEPT d
 	USING(DEPTNO)
 	GROUP BY ROLLUP(DNAME, JOB)
 	ORDER BY 1, 2;
 
-- SQLD 문제 : ROLLUP을 사용할 때 ROLLUP(MGR, DNAME, JOB) - 연산자 우선순위
-- 1) ROLLUP(MGR, DNAME, JOB)
-- 2) ROLLUP(MGR, (DNAME, JOB))
-- 3) ROLLUP((MGR, DNAME, JOB))
 
SELECT --DNAME, JOB, 
	--CASE GROUPING(MGR) WHEN 1 THEN '모든 매니저' ELSE MGR END AS 매니저 , 
 	CASE GROUPING(DNAME) WHEN 1 THEN '모든부서' ELSE DNAME END AS 부서 , 
 	CASE GROUPING(JOB) WHEN 1 THEN '모든업무' ELSE JOB END AS 업무, 
 	COUNT(*), SUM(SAL)
 	FROM EMP e JOIN DEPT d
 	USING(DEPTNO)
 	--GROUP BY ROLLUP(MGR, DNAME, JOB)	--MGR -> MGR+DNAME -> MGR + DNAME + JOB : 27개
 	--GROUP BY ROLLUP(MGR, (DNAME, JOB)) --MGR -> MGR + (DNAME+JOB) : 18개
 	GROUP BY ROLLUP((MGR, DNAME, JOB))	--MGR+DNAME+JOB : 11개
 	ORDER BY 1, 2; 

 
 -- 간단작업 확인
SELECT JOB, DNAME, COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY ROLLUP(JOB, DNAME)
	ORDER BY JOB, DNAME	--15개 JOB, JOB+DNAME
	
	SELECT JOB, DNAME, COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	GROUP BY ROLLUP((JOB, DNAME))	--10개
	ORDER BY JOB, DNAME;
	
-- CUBE 다차원 통계 : 발생할 수 있는 모든 소계, 총계에 대한 정보를 출력해 준다
-- ROLLUP(DNAME, JOB) - DNAME 통계 , DNAME+JOB 통계
-- CUBE(DNAME, JOB) - DNAME 통계 , JOB 통계 , DNAME+JOB 통계

SELECT  DNAME, JOB,  COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d 
	USING(DEPTNO)
	GROUP BY ROLLUP(DNAME, JOB)
	ORDER BY DNAME, JOB ; 	-- 13개 : 1줄 ACCOUNTING, RESEARCH, SALES = 전체 통계 14/22400
--										1줄 ACCOUNTING
--										1줄 RESEARCH
--										1줄 SALES
--										각 ACCOUNTING 3줄, RESERACH 3줄, SALES 3줄
	
SELECT  DNAME, JOB,  COUNT(*), SUM(SAL)
	FROM EMP e JOIN DEPT d 
	USING(DEPTNO)
	GROUP BY CUBE(DNAME, JOB)
	ORDER BY DNAME, JOB ;

-- GROUPING SETS(컬럼) : 작성한 컬럼만 통계를 작성 하여 출력
-- CVAS를 통해서 많이 사용하는 SQL을 메소드처럼 만들어서 사용한다 => VIEW

CREATE VIEW EMPNDEPT AS (SELECT DNAME, JOB, SAL
							FROM EMP e JOIN DEPT d
							USING(DEPTNO));
	
SELECT *
	FROM EMPNDEPT e ;

SELECT JOB, COUNT(*), SUM(SAL)
	FROM EMPNDEPT e 
	GROUP BY GROUPING SETS(JOB);

SELECT DNAME, JOB, COUNT(*), SUM(SAL)
	FROM EMPNDEPT e 
	GROUP BY GROUPING SETS(JOB, DNAME);	--DNAME 3개, JOB 5개
	
-- GROUP BY ROLLUP, CUBE, GROUPING SETS를 UNION ALL을 통해서 작성해라
-- 4개의 컬럼
-- DNAME, JOB, COUNT(*), SUM(SAL)
-- 1단계 DNAME별의 소계
SELECT DNAME, '',COUNT(*), SUM(SAL)
	FROM EMPNDEPT e
	GROUP BY DNAME
UNION ALL
-- 2단계 JOB의 소계
SELECT '', JOB, COUNT(*), SUM(SAL)
	FROM EMPNDEPT e 
	GROUP BY JOB;
 











