
COMMIT;

INSERT INTO USERINFO (SEQ, NAME, TEL, ROLE, CREATEAT)
	VALUES(USERINFO_SEQ.NEXTVAL, '홍길동', '01011112222', 'A', SYSDATE);

UPDATE PLAYER 
	SET NICKNAME = 'SQL마스터'
	WHERE PLAYER_ID = '2026001';
	
DELETE FROM PLAYER 
	WHERE TEAM_ID = 'K01';

SELECT e.ENAME , e.SAL , NVL(e.COMM, 0)
	FROM EMP e;

SELECT p.PLAYER_ID , p.PLAYER_NAME , p.TEAM_ID 
	FROM PLAYER p
	WHERE p.PLAYER_NAME LIKE '김%';

SELECT *
	FROM (SELECT e.ENAME , e.SAL 
		FROM EMP e
		ORDER BY SAL DESC)
	WHERE ROWNUM <= 3;

ROLLBACK;