-- 전체조회
SELECT e.EMPNO, e.ENAME , e.JOB , TO_CHAR(e.HIREDATE, 'YYYY-MM-DD') HDATE, e.DEPTNO 
	FROM EMP e
	ORDER BY e.HIREDATE DESC; 

-- 상세조회
SELECT e.EMPNO, e.ENAME , e.JOB , TO_CHAR(e.HIREDATE, 'YYYY-MM-DD') HDATE, DEPTNO, d.DNAME
	FROM EMP e JOIN DEPT d
	USING(DEPTNO)
	WHERE EMPNO = '7698';

-- 입력
INSERT INTO EMP (EMPNO, ENAME, HIREDATE, 
				DEPTNO)
			VALUES( (SELECT MAX(EMPNO) + 1 FROM EMP),
			'TEST', SYSDATE, 20
			);

-- 삭제
DELETE FROM EMP
	WHERE EMPNO = '7935';

-- 수정
UPDATE EMP e SET JOB = 'IT'
	WHERE EMPNO = '7369';